# Generated by Django 3.2.25 on 2025-07-10 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Time_minutes',
            new_name='time_minutes',
        ),
    ]
