# This is the configuration for GitHub Actions to run checks on your code.
---
name: Checks

on: [push] # This is the trigger for the workflow.

jobs:
    test-lint:
        name: Test and Lint # This is the name of the job that will run.
        runs-on: ubuntu-22.04 # This specifies the type of runner to use.
        steps: # This is the steps that will be executed in the job.
            - name: Login to DockerHub # This step logs in to DockerHub. you will see it in GitHub interface.
              uses: docker/login-action@v1 
              with:
                username: ${{ secrets.DOCKERHUB_USER }} # Use your DockerHub username from secrets.
                password: ${{ secrets.DOCKERHUB_TOKEN }} # Use your DockerHub password from secrets.

            - name: Checkout 
              uses: actions/checkout@v2 # This step checks out your code from the repository.
            - name: Test
              run: docker compose run --rm app sh -c ""python manage.py wait_for_db && python manage.py test"
            - name: Lint
              run: docker compose run --rm app sh -c "flake8"
